apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-configmap
  labels:
    app: phpmyadmin-app
data:
  PMA_ARBITRARY: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin-app
spec:
  selector:
    app: phpmyadmin-app
  ports:
    - port: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phpmyadmin-app
  template:
    metadata:
      labels:
        app: phpmyadmin-app
    spec:
      containers:
        - name: phpmyadmin-container
          image: phpmyadmin
          envFrom:
            - configMapRef:
                name: phpmyadmin-configmap
