apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment-brian
  labels:
    app: myapp-brian
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-brian
  template:
    metadata:
      labels:
        app: myapp-brian
    spec:
      containers:
        - name: myapp-container
          image: ghcr.io/stefanprodan/podinfo:6.0.0
          envFrom:
            - configMapRef:
                name: myapp-config-brian
