apiVersion: v1
kind: Service
metadata:
  name: myapp-service-brian
  labels:
    app: myapp-brian
spec:
  selector:
    app: myapp-brian
  ports:
    - protocol: TCP
      port: 9898
  type: LoadBalancer
#  type: ClusterIP

